=== ducatinat/TEHM/OSINT/Reaper/sources/source.dtd
<?xml version="1.0"?>
<!ELEMENT source (name,keys,children+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT keys (key*)>
<!ELEMENT key (name,value)>
<!ELEMENT children (node*)>
<!ELEMENT node (name,description*,function,inputs,children*)>
<!ELEMENT inputs (input+)>
<!ELEMENT input (name,type,elems*,columns*,rows*,setters*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT elems (elem*)>
<!ELEMENT elem (#PCDATA)>
<!ELEMENT rows (row*)>
<!ELEMENT row (cell*)>
<!ELEMENT cell (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT setters (setter*)>
<!ELEMENT setter (name,argument,value,type)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT function (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST input required CDATA #IMPLIED>

=== ducatinat/TEHM/OSINT/Reaper/sources/tumblr.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
    <name>Tumblr</name>
    <keys>
        <key>
            <name>API key</name>
            <value>api_key</value>
        </key>
    </keys>
    <children>
        <node>
            <name>Blog</name>
            <function>blog_info</function>
            <inputs>
                <input>
                    <name>Blog id</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                </input>
            </inputs>
            <children>
                <node>
                    <name>Posts</name>
                    <function>blog_posts</function>
                    <inputs>
                        <input>
                            <name>Blog id</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Arguments</name>
                            <type>arguments</type>
                            <columns>
                                <column>Argument</column>
                                <column>Value</column>
                            </columns>
                            <setters>
                                <setter>
                                    <name>Post type</name>
                                    <argument>type</argument>
                                    <value>text,quote,link,answer,video,audio,photo,char</value>
                                    <type>list</type>
                                </setter>
                                <setter>
                                    <name>Post count</name>
                                    <argument>count</argument>
                                    <value>500</value>
                                    <type>counter</type>
                                </setter>
                                <setter>
                                    <name>Include reblog info</name>
                                    <argument>reblog_info</argument>
                                    <value>False</value>
                                    <type>checkbox</type>
                                </setter>
                                <setter>
                                    <name>Include notes info</name>
                                    <argument>notes_info</argument>
                                    <value>False</value>
                                    <type>checkbox</type>
                                </setter>
                                <setter>
                                    <name>Filter</name>
                                    <argument>filter</argument>
                                    <value>text,raw</value>
                                    <type>list</type>
                                </setter>
                            </setters>
                        </input>
                    </inputs>
                    <children/>
                </node>
            </children>
        </node>
        <node>
            <name>Tag</name>
            <function>tag_posts</function>
            <description>Tag's Posts</description>
            <inputs>
                <input>
                    <name>Tag</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Post count</name>
                            <argument>count</argument>
                            <value>500</value>
                            <type>counter</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
    </children>
</source>

=== ducatinat/TEHM/OSINT/Reaper/sources/twitter.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
    <name>Twitter</name>
    <keys>
        <key>
            <name>API key</name>
            <value>api_key</value>
        </key>
        <key>
            <name>API secret</name>
            <value>api_secret</value>
        </key>
        <key>
            <name>Access token</name>
            <value>access_token</value>
        </key>
        <key>
            <name>Access token secret</name>
            <value>access_token_secret</value>
        </key>
    </keys>
    <children>
        <node>
            <name>Search</name>
            <description>Search's tweets</description>
            <function>search</function>
            <inputs>
                <input required="true">
                    <name>Query</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Tweet count</name>
                            <argument>count</argument>
                            <value>500</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Include entities</name>
                            <argument>include_entities</argument>
                            <value>True</value>
                            <type>checkbox</type>
                        </setter>
                        <setter>
                            <name>Text length</name>
                            <argument>tweet_mode</argument>
                            <value>extended,compat</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
        <node>
            <name>User</name>
            <description>User's tweets</description>
            <function>user</function>
            <inputs>
                <input required="true">
                    <name>User</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Tweet count</name>
                            <argument>count</argument>
                            <value>3200</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Exclude replies</name>
                            <argument>exclude_replies</argument>
                            <value>True</value>
                            <type>checkbox</type>
                        </setter>
                        <setter>
                            <name>Include retweets</name>
                            <argument>include_retweets</argument>
                            <value>False</value>
                            <type>checkbox</type>
                        </setter>
                        <setter>
                            <name>Text length</name>
                            <argument>tweet_mode</argument>
                            <value>extended,compat</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
    </children>
</source>

=== ducatinat/TEHM/OSINT/Reaper/sources/pinterest.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
    <name>Pinterest</name>
    <keys>
        <key>
            <name>Access token</name>
            <value>access_token</value>
        </key>
    </keys>
    <children>
        <node>
            <name>User</name>
            <function>user</function>
            <inputs>
                <input>
                    <name>Username</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Fields</name>
                    <type>list</type>
                    <elems>
                        <elem>id</elem>
                        <elem>username</elem>
                        <elem>first_name</elem>
                        <elem>last_name</elem>
                        <elem>bio</elem>
                        <elem>created_at</elem>
                        <elem>counts</elem>
                        <elem>image</elem>
                    </elems>
                </input>
            </inputs>
            <children>
                <node>
                    <name>Boards</name>
                    <function>user_boards</function>
                    <inputs>
                        <input>
                            <name>User</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Fields</name>
                            <type>list</type>
                            <elems>
                                <elem>id</elem>
                                <elem>name</elem>
                                <elem>url</elem>
                                <elem>description</elem>
                                <elem>creator</elem>
                                <elem>created_at</elem>
                                <elem>counts</elem>
                                <elem>image</elem>
                            </elems>
                        </input>
                    </inputs>
                    <children/>
                </node>
                <node>
                    <name>Pins</name>
                    <function>user_pins</function>
                    <inputs>
                        <input>
                            <name>User</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Fields</name>
                            <type>list</type>
                            <elems>
                                <elem>id</elem>
                                <elem>link</elem>
                                <elem>url</elem>
                                <elem>creator</elem>
                                <elem>board</elem>
                                <elem>created_at</elem>
                                <elem>note</elem>
                                <elem>color</elem>
                                <elem>counts</elem>
                                <elem>media</elem>
                                <elem>attribution</elem>
                                <elem>image</elem>
                                <elem>metadata</elem>
                            </elems>
                        </input>
                    </inputs>
                    <children/>
                </node>
            </children>
        </node>
        <node>
            <name>Board</name>
            <function>board</function>
            <inputs>
                <input>
                    <name>User</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Board</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Fields</name>
                    <type>list</type>
                    <elems>
                        <elem>id</elem>
                        <elem>name</elem>
                        <elem>url</elem>
                        <elem>description</elem>
                        <elem>creator</elem>
                        <elem>created_at</elem>
                        <elem>counts</elem>
                        <elem>image</elem>
                    </elems>
                </input>
            </inputs>
            <children>
                <node>
                    <name>Pins</name>
                    <function>board_pins</function>
                    <inputs>
                        <input>
                            <name>User</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Board</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Fields</name>
                            <type>list</type>
                            <elems>
                                <elem>id</elem>
                                <elem>link</elem>
                                <elem>url</elem>
                                <elem>creator</elem>
                                <elem>board</elem>
                                <elem>created_at</elem>
                                <elem>note</elem>
                                <elem>color</elem>
                                <elem>counts</elem>
                                <elem>media</elem>
                                <elem>attribution</elem>
                                <elem>image</elem>
                                <elem>metadata</elem>
                            </elems>
                        </input>
                    </inputs>
                    <children/>
                </node>
            </children>
        </node>
        <node>
            <name>Pin</name>
            <function>pin</function>
            <inputs>
                <input>
                    <name>Pin</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Fields</name>
                    <type>list</type>
                    <elems>
                        <elem>id</elem>
                        <elem>link</elem>
                        <elem>url</elem>
                        <elem>creator</elem>
                        <elem>board</elem>
                        <elem>created_at</elem>
                        <elem>note</elem>
                        <elem>color</elem>
                        <elem>counts</elem>
                        <elem>media</elem>
                        <elem>attribution</elem>
                        <elem>image</elem>
                        <elem>metadata</elem>
                    </elems>
                </input>
            </inputs>
            <children/>
        </node>
    </children>
</source>

=== ducatinat/TEHM/OSINT/Reaper/sources/reddit.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
    <name>Reddit</name>
    <keys>
        <key>
            <name>Application id</name>
            <value>application_id</value>
        </key>
        <key>
            <name>Application secret</name>
            <value>application_secret</value>
        </key>
    </keys>
    <children>
        <node>
            <name>Search</name>
            <function>search</function>
            <description>Search's Threads</description>
            <inputs>
                <input required="true">
                    <name>Query</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Order</name>
                            <argument>order</argument>
                            <value>top,new,relevance,comments</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Thread count</name>
                            <argument>count</argument>
                            <value>1000</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Time period</name>
                            <argument>time_period</argument>
                            <value>all,year,month,week,today,hour</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
        <node>
            <name>Subreddit</name>
            <function>subreddit</function>
            <description>Subreddit's Threads</description>
            <inputs>
                <input required="true">
                    <name>Subreddit</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Category</name>
                            <argument>category</argument>
                            <value>top,new,hot,rising,controversial</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Thread count</name>
                            <argument>count</argument>
                            <value>1000</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Time period</name>
                            <argument>time_period</argument>
                            <value>all,year,month,week,today,hour</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
        <node>
            <name>User</name>
            <function>user</function>
            <description>User's Threads and Comments</description>
            <inputs>
                <input required="true">
                    <name>User</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Result type</name>
                            <argument>result_type</argument>
                            <value>overview,submitted,comments,guilded</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Result count</name>
                            <argument>count</argument>
                            <value>1000</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Order</name>
                            <argument>time_period</argument>
                            <value>new,hot,top,controversial</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
        <node>
            <name>Thread</name>
            <function>thread</function>
            <inputs>
                <input required="true">
                    <name>Thread id</name>
                    <type>primary</type>
                </input>
                <input required="true">
                    <name>Subreddit</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                </input>
            </inputs>
            <children>
                <node>
                    <name>Comments</name>
                    <function>thread_comments</function>
                    <inputs>
                        <input required="true">
                            <name>Thread id</name>
                            <type>primary</type>
                        </input>
                        <input required="true">
                            <name>Subreddit</name>
                            <type>primary</type>
                        </input>
                        <input>
                            <name>Arguments</name>
                            <type>arguments</type>
                            <columns>
                                <column>Argument</column>
                                <column>Value</column>
                            </columns>
                            <setters>
                                <setter>
                                    <name>Comment count</name>
                                    <argument>count</argument>
                                    <value>500</value>
                                    <type>counter</type>
                                </setter>
                                <setter>
                                    <name>Comment order</name>
                                    <argument>order</argument>
                                    <value>top,new,best,controversial,old,q&amp;a</value>
                                    <type>list</type>
                                </setter>
                            </setters>
                        </input>
                    </inputs>
                    <children></children>
                </node>
            </children>
        </node>
    </children>
</source>
